version: 2
updates:
  - package-ecosystem: "npm" # Meninjau pembaruan untuk package.json
    directory: "/"
    schedule:
      interval: "daily" # Cek setiap hari
    open-pull-requests-limit: 10 # Maksimal 10 PR terbuka sekaligus
    labels:
      - "dependencies"
      - "security"
